### ISSUE TITLE
can please provide stf-appium-example in which appium test cases are in java

### ISSUE THREAD

**Issue by prashanthd** [vbanthia/stf-appium-example#1]
Hi ,
I am creating it as issue because not able to contact you.
can please provide stf-appium-example in which appium test cases are in java

**Comment by vbanthia-zz** [comment]
Sorry, I never used Appium Java client before and lately I don't have much free time to work on this project.

Also, the aim behind this tutorial was to show users how to use STF REST API not appium tutorial. I think you can easily find some good appium tutorial in Java on internet.
