### ISSUE TITLE
OpenSTF Appium Integration Issue

### ISSUE THREAD

**Issue by NareshJain91** [vbanthia/stf-appium-example#2]
Hello Vishal,

I went through you github for OpenSTF Appium Integration

As per the readme file I have set up:-
var SWAGGER_URL = 'http://MY_IP_ADDRESS:7100/api/v1/swagger.json'
var AUTH_TOKEN  = '27b7e30c39f146ca84206974a94a52c01d7aca22c2044893843b66bd4c6069f9';

and placed your demo app in Desktop (i am a mac user)
when i am running command 
DEVICE_SERIAL=4d003e184b962125 ./scripts/run_integration_test.sh
from CMD, its show "Cannot connect to device" 

Can you please help me where i am going wrong
Thanks in Advance

**Comment by vbanthia-zz** [comment]
You will have to use stf-v2.0.0 to use API. v2.0.0 is still in beta, so you will have to install it by checking out 2.0.0 branch.

**Comment by NareshJain91** [comment]
Hello @vbanthia  I did that,

now it is showing 
An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

But android_home is already set

**Comment by NareshJain91** [comment]
Hello @vbanthia 

Error 
Device 192.168.1.139:7401 was not in the list of connected devices (Selenium::WebDriver::Error::UnknownError)

As per the readme file I have set up:-
var SWAGGER_URL = 'http://MY_IP_ADDRESS:7100/api/v1/swagger.json'
var AUTH_TOKEN = '27b7e30c39f146ca84206974a94a52c01d7aca22c2044893843b66bd4c6069f9';

Can you please check

**Comment by C14427818** [comment]
> Hello @vbanthia I did that,
> 
> now it is showing
> An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
> 
> But android_home is already set

I am having the same problem as quoted above. And on some tests with JAVA_HOME, yet both are set. Did you figure out a solution to this? You guys seem to be the only ones making any progress with openSTF and Appium integration. Any help will be much appreciated. Cheers.
