### ISSUE TITLE
Can you tell me how to  Create a new Access Token from Settings > Keys > Access Tokens  ?

### ISSUE THREAD

**Issue by yrguo** [vbanthia/stf-appium-example#3]
Can you tell me how to  Create a new Access Token from Settings > Keys > Access Tokens  ?

**Comment by vbanthia-zz** [comment]
1. Go to Settings > Keys > Access Tokens
2. Press "+" button
3. Write token name in "Title" field
4. Click on "Generate New Token"

This will give you a new token. Don't forget to note it down somewhere, you will not see it again.

**Comment by yrguo** [comment]
I know，but  what's the  token name ？
Is it the device name  SM-G9009D  or  "fcea9744" ？

2016-10-14 

郭艳茹
软件测试工程师 移动互联事业部 科大讯飞股份有限公司

邮箱：yrguo@iflytek.com 手机：13615696774
地址：安徽省合肥市望江西路666号讯飞大厦

发件人：Vishal Banthia notifications@github.com
发送时间：2016-10-14 17:20
主题：Re: [openstf/stf-appium-example] Can you tell me how to Create a new Access Token from Settings > Keys > Access Tokens ? (#3)
收件人："openstf/stf-appium-example"stf-appium-example@noreply.github.com
抄送："yrguo"yrguo@iflytek.com,"Author"author@noreply.github.com

Go to Settings > Keys > Access Tokens 
Press "+" button 
Write token name in "Title" field 
Click on "Generate New Token" 
This will give you a new token

**Comment by sorccu** [comment]
Does not matter... It's only for your own use so that you have an idea of what the token is for.

**Comment by yrguo** [comment]
Do you know the reason  for  Cannot connect to device ？

2016-10-14 

郭艳茹
软件测试工程师 移动互联事业部 科大讯飞股份有限公司

邮箱：yrguo@iflytek.com 手机：13615696774
地址：安徽省合肥市望江西路666号讯飞大厦

发件人：Simo Kinnunen notifications@github.com
发送时间：2016-10-14 17:34
主题：Re: [openstf/stf-appium-example] Can you tell me how to Create a new Access Token from Settings > Keys > Access Tokens ? (#3)
收件人："openstf/stf-appium-example"stf-appium-example@noreply.github.com
抄送："yrguo"yrguo@iflytek.com,"Author"author@noreply.github.com

Does not matter... It's only for your own use so that you have an idea of what the token is for.

**Comment by varundtsfi** [comment]
Hi @vbanthia Can you tell me how to copy my host .android/adbkey.pub key inside the android device using nodejs.

I have tried the using open stf if I generate the key's then for other devices also I will not ask for RSA popup because that system keys are already pushed inside the device. You are storing those(client) keys inside the db(rethink).

Please help me I want to implement the same in my project I study your code but still helpless I am new in node and android

**Comment by sorccu** [comment]
You can't. It works in STF because STF pretends to be a device, and then forwards all the traffic to the device itself. It's like a proxy. STF's key is only used for authentication. The device never trusts that key, it doesn't even know it exists.
