### ISSUE TITLE
Could not find a connected Android device.

### ISSUE THREAD

**Issue by headshot289** [vbanthia/stf-appium-example#5]
error message:

yangrenjiedeMacBook-Pro:stf-appium-example yangrenjie$ DEVICE_SERIAL=e241c46d ./scripts/run_integration_test.sh
172.16.19.52:7433
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 172.16.19.52:7433
Running all tests
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib:/Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-support-3.4.1/lib /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Finished in 23.78 seconds (files took 0.63881 seconds to load)
0 examples, 0 failures

/Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device. (Selenium::WebDriver::Error::UnknownError)
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:56:in `new'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:56:in `for'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver.rb:86:in `for'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/appium_lib-8.0.0/lib/appium_lib/driver.rb:484:in `start_driver'
	from /Users/yangrenjie/git289/stf-appium-example/spec/spec_helper.rb:27:in `block (2 levels) in <top (required)>'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:424:in `instance_exec'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:424:in `instance_exec'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:357:in `run'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1724:in `block in run_hooks_with'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1724:in `each'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1724:in `run_hooks_with'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1679:in `with_suite_hooks'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/lib:/Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-support-3.4.1/lib /Users/yangrenjie/git289/stf-appium-example/bundler/vendor/ruby/2.0.0/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
Releasing device
Device disconnected successfully!

**Comment by vbanthia-zz** [comment]
Most probably your device is not authenticated. When you run this command, you will see a popup on STF UI,  Add ADB key from STF UI and rerun tests.
