### ISSUE TITLE
Permission denied (publickey) to download example

### ISSUE THREAD

**Issue by ricardo-valtierra** [vbanthia/stf-appium-example#6]
Hi, thank you very much for the example provided. I've been working great with STF for Android studio. Now I'm getting introduced to the testing area, in which i'm pretty new. That's why I tried to download the present example to test with appium and IntelliJ Idea, but the download wasn't successful. It would be great if you could give any kind of feedback. Thanks in advance

Ricardo Valtierra

I share the error that Ubuntu 16.04 terminal throws me:

git clone git@github.com:openstf/stf-appium-example.git
**Cloning into 'stf-appium-example'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.**

**Comment by vbanthia-zz** [comment]
Use https then `git clone https://github.com/openstf/stf-appium-example.git`
